name: 8 CNB sync
on:
  schedule: [{ cron: "*/30 * * * *" }]
  workflow_dispatch:

jobs:
  call:
    uses: UpCNB/workflows/.github/workflows/cnb-sync.yml@main
    with:
      upstream_repo: https://github.com/tale/headplane
      cnb_repo_url:  https://cnb.cool/g.h/headplane
      # fork_branch: main
      # push_fork_ff: true
      # open_pr_if_diverged: true
      # delete_ai_branch: true
    secrets: inherit
